[package]
name = "foxy-io"
version = "0.0.4"
edition = "2024"
authors = ["Johan Steffens <johan@steff.co.za>"]
description = "A configuration-driven and hyper-extensible HTTP proxy library"
license = "MPL-2.0"
repository = "https://github.com/johan-steffens/foxy"
readme = "README.md"
keywords = ["http", "proxy", "extensible", "configurable"]
categories = ["web-programming", "network-programming"]

[dependencies]
# Async runtime
tokio = { version = "1.28", features = ["full"] }

# Error handling
thiserror = "1.0"

# Serialization/Deserialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.7"

# Optional YAML support
serde_yaml = { version = "0.9", optional = true }

# HTTP and networking
hyper = { version = "1.6.0", features = ["server", "http1"] }
hyper-util = { version = "0.1.3", features = ["tokio"] }
http-body-util = "0.1.0"
bytes = "1.5.0"

# Testing utilities
tempfile = "3.6"
reqwest = "0.12.15"
async-trait = "0.1.88"
log = "0.4.27"
regex = "1.11.1"
env_logger = "0.11.8"
url = "2.5.4"

[features]
default = []
yaml = ["dep:serde_yaml"]

[lib]
name = "foxy"
path = "src/lib.rs"

[[example]]
name = "basic-proxy"
path = "examples/basic-proxy/main.rs"